spring.profiles.active: dev

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:com/enlink/auth/dao/mapper/xml/*Mapper.xml
  type-aliases-package: com.enlink.auth.dao.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro_auth?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: myuser
    password: mypassword
    tomcat:
      max-active: 20
      max-idle: 10
      min-idle: 1
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1

# auth_center本身是个微服务，因为它提供获取密钥和微信授权这样的服务
authserver:
  # 微服务名，必须配置
  serverName: micro_auth
  # 需要进行微服务Token检查的路径列表，根据需要配置
  needMicroTokenCheckPaths:
    # 获取密钥接口
    - /auth/secret
    - /customerOauth/**
authcenter:
  business:
    resource:
      - resourceId: bqxz
        appId: wx3eda9d6833de1237
        appKey: 93409f4b1d4bcf4261371cb21ec260c4
        source: weichat